// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_-E9l8LCzcXuxK_AomIAdHTE_rUAe5Bw',
    appId: '1:936891662373:web:4bbdf5ccaf91115f563fcc',
    messagingSenderId: '936891662373',
    projectId: 'test-fa47e',
    authDomain: 'test-fa47e.firebaseapp.com',
    storageBucket: 'test-fa47e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZVK4Gdtuc_FjghnSWSOzhzwmQSRhOuNU',
    appId: '1:936891662373:android:1774c082d41f51a5563fcc',
    messagingSenderId: '936891662373',
    projectId: 'test-fa47e',
    storageBucket: 'test-fa47e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwDdTfA563tJY9m6ttPStj36dNB2qlEMg',
    appId: '1:936891662373:ios:b00302fac7b21d83563fcc',
    messagingSenderId: '936891662373',
    projectId: 'test-fa47e',
    storageBucket: 'test-fa47e.firebasestorage.app',
    iosClientId: '936891662373-3v7cn6aer5n4kq8lifmaubb0hnnv33ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwDdTfA563tJY9m6ttPStj36dNB2qlEMg',
    appId: '1:936891662373:ios:b00302fac7b21d83563fcc',
    messagingSenderId: '936891662373',
    projectId: 'test-fa47e',
    storageBucket: 'test-fa47e.firebasestorage.app',
    iosClientId: '936891662373-3v7cn6aer5n4kq8lifmaubb0hnnv33ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.gameApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_-E9l8LCzcXuxK_AomIAdHTE_rUAe5Bw',
    appId: '1:936891662373:web:b44fd63841736ae5563fcc',
    messagingSenderId: '936891662373',
    projectId: 'test-fa47e',
    authDomain: 'test-fa47e.firebaseapp.com',
    storageBucket: 'test-fa47e.firebasestorage.app',
  );

}